+ + ipv6 option

diff --git a/firewalld b/firewalld
--- a/firewalld
+++ b/firewalld
@@ -43,9 +43,42 @@ APK="$(which apk)"
 SCRIPT="$0"
 
 #|--------------------------------------------------------------------------
+#| Arguments & Usage Help
+#|--------------------------------------------------------------------------
+
+# Usage
+function usage() {
+    echo "Usage: $0 [options]"
+    echo "Options:"
+    echo "  -ipv6, --ipv6           Setup IPv6 ipsets"
+    echo "  -h, --help              Show this message (help)"
+    exit 0
+}
+
+# Arguments
+while [[ $# -gt 0 ]]; do
+    key="$1"
+    case $key in
+        -ipv6|--ipv6)
+            _IPV6=1
+            shift
+            shift
+            ;;
+        -h|--help)
+            usage
+            ;;
+        *)
+            echo "Unknown option: $1"
+            exit 1
+            ;;
+    esac
+done
+
+#|--------------------------------------------------------------------------
 #| Main
 #|--------------------------------------------------------------------------
 
+# Detecting the OS
 if [[ -x "$YUM" ]]; then
     OS="RHEL"
     echo -e "[${PURPLE}i${NC}] Detected operating system as RHEL/CentOS"
@@ -57,6 +90,7 @@ else
 	exit 1
 fi
 
+# Detecting if firewalld is available
 echo -e "[${PURPLE}i${NC}] Verifying if firewalld is available"
 if ! [[ -x "$FIREWALLD" ]]; then
     echo -e "[${PURPLE}i${NC}] firewalld not available, installing"
@@ -85,6 +119,7 @@ fi
 
 echo ""
 
+# Check existing IPv4 ipset
 echo -e "[${PURPLE}i${NC}] Checking for existing ipset for ${BLACKLIST}-ip4"
 if firewall-cmd --permanent --get-ipsets | grep -q "${BLACKLIST}-ip4"; then
     echo -e "[${PURPLE}i${NC}] Deleting ipset ${BLACKLIST}-ip4"
@@ -93,6 +128,7 @@ if firewall-cmd --permanent --get-ipsets | grep -q "${BLACKLIST}-ip4"; then
     firewall-cmd --permanent --delete-ipset="${BLACKLIST}-ip4" &> /dev/null
 fi
 
+# Create the IPv4 ipset
 echo -e "[${PURPLE}i${NC}] Creating new ipset for ${BLACKLIST}-ip4"
 firewall-cmd --permanent --new-ipset="${BLACKLIST}-ip4" --type=hash:net --option=family=inet --option=hashsize=4096 --option=maxelem=200000 --zone=drop > /dev/null 2> /dev/null 
 if [[ $? -eq 0 ]];then
@@ -104,24 +140,32 @@ fi
 
 echo ""
 
-echo -e "[${PURPLE}i${NC}] Checking for existing ipset for ${BLACKLIST}-ip6"
-if firewall-cmd --permanent --get-ipsets | grep -q "${BLACKLIST}-ip6"; then
-    echo -e "[${PURPLE}i${NC}] Deleting ipset ${BLACKLIST}-ip6"
-    firewall-cmd --permanent --zone=drop --remove-source=ipset:"${BLACKLIST}-ip6" &> /dev/null
-    firewall-cmd --reload &> /dev/null
-    firewall-cmd --permanent --delete-ipset="${BLACKLIST}-ip6" &> /dev/null 
-fi
+function checking_exist_ipv6_ipset(){
 
-echo -e "[${PURPLE}i${NC}] Creating new ipset for ${BLACKLIST}-ip6"
-firewall-cmd --permanent --new-ipset="${BLACKLIST}-ip6" --type=hash:net --option=family=inet6 --option=hashsize=4096 --option=maxelem=200000 --zone=drop > /dev/null 2> /dev/null 
-if [[ $? -eq 0 ]];then
-    echo -e "[${GREEN}✓${NC}] ipset for ${BLACKLIST}-ip6 successfully created"
-else
-    echo -e "[${RED}✗${NC}] Couldn't create the blacklist ${BLACKLIST}-ip6. Aborting!"
-    exit 1
-fi
+    echo -e "[${PURPLE}i${NC}] Checking for existing ipset for ${BLACKLIST}-ip6"
+    if firewall-cmd --permanent --get-ipsets | grep -q "${BLACKLIST}-ip6"; then
+        echo -e "[${PURPLE}i${NC}] Deleting ipset ${BLACKLIST}-ip6"
+        firewall-cmd --permanent --zone=drop --remove-source=ipset:"${BLACKLIST}-ip6" &> /dev/null
+        firewall-cmd --reload &> /dev/null
+        firewall-cmd --permanent --delete-ipset="${BLACKLIST}-ip6" &> /dev/null 
+    fi
 
-echo ""
+}
+
+function create_ipv6_ipset(){
+
+    echo -e "[${PURPLE}i${NC}] Creating new ipset for ${BLACKLIST}-ip6"
+    firewall-cmd --permanent --new-ipset="${BLACKLIST}-ip6" --type=hash:net --option=family=inet6 --option=hashsize=4096 --option=maxelem=200000 --zone=drop > /dev/null 2> /dev/null 
+    if [[ $? -eq 0 ]];then
+        echo -e "[${GREEN}✓${NC}] ipset for ${BLACKLIST}-ip6 successfully created"
+    else
+        echo -e "[${RED}✗${NC}] Couldn't create the blacklist ${BLACKLIST}-ip6. Aborting!"
+        exit 1
+    fi
+
+    echo ""
+
+}
 
 # Create the tmp directory
 mkdir -p $TMPDIR
@@ -164,21 +208,32 @@ for f in $TMPDIR/*-ip4.zone; do
     echo ""
 done
 
-for f in $TMPDIR/*-ip6.zone; do
-    echo -e "[${PURPLE}i${NC}] Adding ipv6 target ranges from ${YELLOW}$f${NC}"
-    firewall-cmd --permanent --ipset="${BLACKLIST}-ip6" --add-entries-from-file=$f > /dev/null
-    if [[ $? -eq 0 ]];then
-        echo -e "[${GREEN}✓${NC}] OK"
-    else
-        echo -e "[${RED}✗${NC}] Failed"
-    fi
-    echo ""
-done
+function adding_ipv6_ranges(){
+
+    for f in $TMPDIR/*-ip6.zone; do
+        echo -e "[${PURPLE}i${NC}] Adding ipv6 target ranges from ${YELLOW}$f${NC}"
+        firewall-cmd --permanent --ipset="${BLACKLIST}-ip6" --add-entries-from-file=$f > /dev/null
+        if [[ $? -eq 0 ]];then
+            echo -e "[${GREEN}✓${NC}] OK"
+        else
+            echo -e "[${RED}✗${NC}] Failed"
+        fi
+        echo ""
+    done
+
+}
 
 # Initialize the firewall
 echo -e "[${PURPLE}i${NC}] Initializing firewalld"
 firewall-cmd --permanent --zone=drop --add-source="ipset:${BLACKLIST}-ip4" > /dev/null
-firewall-cmd --permanent --zone=drop --add-source="ipset:${BLACKLIST}-ip6" > /dev/null
+
+
+if [[ "$_IPV6" -eq "1" ]]; then
+    checking_exist_ipv6_ipset
+    create_ipv6_ipset
+    adding_ipv6_ranges
+    firewall-cmd --permanent --zone=drop --add-source="ipset:${BLACKLIST}-ip6" > /dev/null
+fi
 
 # Reload the firewall
 echo -e "[${PURPLE}i${NC}] Reloading firewalld"
@@ -190,5 +245,10 @@ rm -rf $TMPDIR
 
 echo ""
 
-echo -e "[${PURPLE}i${NC}] Blocking approx. ${YELLOW}$(ipset list ${BLACKLIST}-ip4 | wc -l)${NC} ipv4 target ranges and approx. ${YELLOW}$(ipset list ${BLACKLIST}-ip6 | wc -l)${NC} ipv6 target ranges."
+echo -e "[${PURPLE}i${NC}] Blocking approx. ${YELLOW}$(ipset list ${BLACKLIST}-ip4 | wc -l)${NC} ipv4 target ranges and approx."
+
+if [[ "$_IPV6" -eq "1" ]]; then
+    echo -e "[${PURPLE}i${NC}] Blocking approx. ${YELLOW}$(ipset list ${BLACKLIST}-ip6 | wc -l)${NC} ipv6 target ranges."
+fi
+
 echo -e "[${GREEN}✓${NC}] Firewall successfully configured!"
